fails:The break statement in a captured block when the invocation of the scope creating the block is still active raises a LocalJumpError when yielding to the block
fails:The break statement in a lambda when the invocation of the scope creating the lambda is still active raises a LocalJumpError when yielding to a lambda passed as a block argument
fails:The break statement in a lambda from a scope that has returned returns a value to the method scope invoking the lambda
fails:The break statement in a lambda from a scope that has returned returns a value to the block scope invoking the lambda in a method
fails:Executing break from within a block returns from the original invoking method even in case of chained calls
