fails:Hash.try_convert does not rescue exceptions raised by #to_hash
